x-google-allow: all
swagger: "2.0"
info:
  title: "video-captions-api"
  version: "0.1.0"
host: "video-captions-api.endpoints.nyt-video-prd.cloud.goog"

paths:
  "/**":
    get:
      operationId: "wildcard-get"
      responses:
        default:
          description: "wildcard-response"
      security: []
    post:
      operationId: "wildcard-post"
      responses:
        default:
          description: "wildcard-response"
      security: []
